
spring: 
  datasource: 
    url: jdbc:mysql://localhost:3306/redisdb?createDatabaseIfNotExist=true 
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    database: mysql
    show-sql: true
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialec
    hibernate:
      ddl-auto: update